version: 1.0.{build}
image: Ubuntu
environment:
  APP_URL: http://localhost
  APP_PORT: 3333
  REDIS_HOST: redis
  REDIS_PORT: 6379
  JWT_EXPIRATION_TIME: 7d
  JWT_SECRET: testing
install:
  - sh: npm ci
test_script:
  - sh: npm run test
on_success:
  - sh: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov

      chmod +x codecov
      ./codecov
